title: blaufish.github.io
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Your Friendly Neighborhood Blaufish.
  Security professional.
  Podcaster.
  Audio, Video editor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: blaufish

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - "*.bak"
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
